"""
Django settings for Algomaat project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

"""

import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = "django-insecure-)gm2g*680yi239m%lkrdqy&1vc=c595b@gk58c^15j@6gywjap"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Comma-separated list of hosts, e.g. "example.com,www.example.com"
ALLOWED_HOSTS = [h.strip() for h in config("ALLOWED_HOSTS", default="*").split(",") if h.strip()]

# Origins allowed for CSRF (required behind HTTPS/reverse proxy), e.g.
# "https://example.com,https://www.example.com"
CSRF_TRUSTED_ORIGINS = [o.strip() for o in config("CSRF_TRUSTED_ORIGINS", default="").split(",") if o.strip()]

ACCOUNT_ACTIVATION_DAYS= 10
# Application definition
EMAIL_HOST = 'localhost'

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    
    "channels",
    "django_htmx",
    "whitenoise.runserver_nostatic",
    
#   "users",
    "contents",
    "bucket",
    "registration",
    #"users",
    "calendarapp.apps.CalendarappConfig",
    "abstracts",
    "material.apps.MaterialConfig",
    "lessonapp",
    "chat",
    "paiement",
    "sitecms",
    "recruitment",
    "espaces",
    #"accounts.apps.AccountsConfig",

    # Refonte 2026 — modules greffés (mail Brevo + paiement mobile money Tara)
    "anymail",
    "django_q",
    "apps_coop.notifications",
    "apps_coop.payments",
    "apps_coop.audit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]



LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
SOCIALACCOUNT_LOGIN_ON_GET = True




ROOT_URLCONF = "Algomaat.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'Algomaat/templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "registration.context_processors.user_is_admin",
            ],
        },
    },
]



AUTHENTICATION_BACKENDS = [

	#needed to login by username in dangoadmin, regardless of allauth
	'django.contrib.auth.backends.ModelBackend',
	
	#allauth specific authentication methods such as login by email
	'allauth.account.auth_backends.AuthenticationBackend',


]





WSGI_APPLICATION = "Algomaat.wsgi.application"
ASGI_APPLICATION = "Algomaat.asgi.application"


#Channels

CHANNEL_LAYERS = {

    "default":{
    
         "BACKEND": "channels.layers.InMemoryChannelLayer"
    
    }

}






# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Uses PostgreSQL when POSTGRES_DB is provided (production / docker),
# falls back to local SQLite otherwise (development).
if config("POSTGRES_DB", default=""):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("POSTGRES_DB"),
            "USER": config("POSTGRES_USER"),
            "PASSWORD": config("POSTGRES_PASSWORD"),
            "HOST": config("POSTGRES_HOST", default="db"),
            "PORT": config("POSTGRES_PORT", default="5432"),
            "CONN_MAX_AGE": config("POSTGRES_CONN_MAX_AGE", default=60, cast=int),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'Algomaat/static')
]

STATIC_ROOT = BASE_DIR/'staticfiles'

# Static files served (and compressed) by WhiteNoise.
# NB: on utilise CompressedStaticFilesStorage (sans manifeste) plutôt que la variante
# "Manifest" : certaines CSS héritées (owl, jquery-ui, STYle2) référencent des images
# absentes, ce qui ferait échouer collectstatic avec le stockage à manifeste strict.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}


MEDIA_ROOT = BASE_DIR/'mediafiles'


# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash if there is a path component (optional in other cases).
# Examples: "http://media.lawrence.com", "http://example.com/media/"
#MEDIA_URL = "/Algomaat/staticfiles/"
MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#configuration parameterEmail configuration setting



# SECRET KEY
SECRET_KEY = config("SECRET_KEY")

# DEBUG
DEBUG = config("DEBUG", default=False, cast=bool)

# Google OAuth
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID", default=""),
            "secret": config("GOOGLE_CLIENT_SECRET", default=""),
            "key": ""
        }
    }
}

# Email — migré vers Brevo via django-anymail (refonte 2026).
# En dev : backend console (rien n'est envoyé, les mails s'affichent dans les logs).
# En prod : EMAIL_BACKEND=anymail.backends.brevo.EmailBackend + BREVO_API_KEY.
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
ANYMAIL = {"BREVO_API_KEY": config("BREVO_API_KEY", default="")}
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="HBC-RH <noreply@humanbcorp.com>")
CONTACT_NOTIFICATION_EMAIL = config("CONTACT_NOTIFICATION_EMAIL", default="contact@humanbcorp.com")
# Anciens réglages SMTP conservés (inertes tant que EMAIL_BACKEND ≠ smtp).
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# Paiement mobile money Tara (app apps_coop.payments).
TARA_API_KEY = config("TARA_API_KEY", default="")
TARA_BUSINESS_ID = config("TARA_BUSINESS_ID", default="")
TARA_WEBHOOK_SECRET = config("TARA_WEBHOOK_SECRET", default="")
# Sert à construire l'URL de webhook envoyée à Tara : {PUBLIC_BASE_URL}/api/v1/payments/webhook/tara/
PUBLIC_BASE_URL = config("PUBLIC_BASE_URL", default="http://localhost:8011")
# URL publique de la vitrine (web/) — sert à construire le lien magique de l'espace apprenant.
SITE_PUBLIC_URL = config("SITE_PUBLIC_URL", default="http://localhost:3000")
# Modes test — À LAISSER FALSE EN PROD (valident les paiements sans Tara / sans contrôle de montant).
PAYMENTS_TEST_AUTO_VALIDATE = config("PAYMENTS_TEST_AUTO_VALIDATE", default=False, cast=bool)
PAYMENTS_TEST_ALLOW_ANY_AMOUNT = config("PAYMENTS_TEST_ALLOW_ANY_AMOUNT", default=False, cast=bool)

# Ordonnanceur django-q2 (cron de réconciliation des paiements EN_ATTENTE).
# Broker = ORM Django (pas de Redis requis). Le cluster ne tourne que si `manage.py qcluster` est lancé.
Q_CLUSTER = {
    "name": "hbc",
    "orm": "default",
    "timeout": 90,
    "retry": 120,
    "workers": 2,
    "catch_up": False,
}

# Chatbot (OpenRouter) — la clé reste côté serveur.
OPENROUTER_API_KEY = config("OPENROUTER_API_KEY", default="")
OPENROUTER_MODEL = config("OPENROUTER_MODEL", default="openai/gpt-4o-mini")


# ---------------------------------------------------------------------------
# Production hardening (active automatically when DEBUG is False)
# ---------------------------------------------------------------------------
# Behind an Nginx/reverse proxy terminating TLS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ---------------------------------------------------------------------------
# Journalisation — sans config explicite, seuls les WARNING+ remontaient et les
# logs INFO (résumés de réconciliation, traces webhook, record_audit best-effort)
# étaient perdus. On formate la console (récupérée par docker/gunicorn) + un
# fichier rotatif optionnel, et on route les ERROR vers `mail_admins` si ADMINS.
# ---------------------------------------------------------------------------
ADMINS = [("Admin HBC", e.strip()) for e in config("ADMINS", default="").split(",") if e.strip()]

LOG_LEVEL = config("LOG_LEVEL", default="INFO")
LOG_DIR = BASE_DIR / "logs"
_log_handlers = ["console"]
try:
    LOG_DIR.mkdir(exist_ok=True)
    _log_handlers.append("file")
except OSError:
    pass  # système de fichiers en lecture seule → on reste sur la console

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "{asctime} {levelname} {name} — {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        **({"file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "hbc.log"),
            "maxBytes": 5 * 1024 * 1024, "backupCount": 5, "formatter": "verbose",
        }} if "file" in _log_handlers else {}),
        "mail_admins": {"class": "django.utils.log.AdminEmailHandler", "level": "ERROR"},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        "django": {"handlers": _log_handlers, "level": "INFO", "propagate": False},
        "django.request": {"handlers": _log_handlers + ["mail_admins"], "level": "ERROR", "propagate": False},
        "apps_coop": {"handlers": _log_handlers, "level": LOG_LEVEL, "propagate": False},
        "recruitment": {"handlers": _log_handlers, "level": LOG_LEVEL, "propagate": False},
        "sitecms": {"handlers": _log_handlers, "level": LOG_LEVEL, "propagate": False},
    },
}

# Tracker d'erreurs Sentry — actif uniquement si SENTRY_DSN est fourni.
SENTRY_DSN = config("SENTRY_DSN", default="")
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=config("SENTRY_TRACES_RATE", default=0.0, cast=float),
            send_default_pii=False,
            environment=config("SENTRY_ENV", default="production"),
        )
    except ImportError:
        pass  # sentry-sdk non installé → on ignore proprement


# ---------------------------------------------------------------------------
# API REST (DRF) + JWT + CORS — pour la stack découplée
#   humanbcorp.com (vitrine Next) · dashboard.humanbcorp.com (CMS Next)
#   api.humanbcorp.com (ce backend Django)
# ---------------------------------------------------------------------------
from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
}

# CORS — origines autorisées des front-ends Next (dev + prod).
CORS_ALLOWED_ORIGINS = [o.strip() for o in config(
    "CORS_ALLOWED_ORIGINS",
    default=(
        "http://localhost:3000,http://localhost:3001,http://localhost:3007,"
        "http://127.0.0.1:3000,http://127.0.0.1:3001,http://127.0.0.1:3007"
    ),
).split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True
# En dev (DEBUG), autoriser tout localhost:<port> ET toute IP privée du réseau
# local : un collaborateur sur le même sous-réseau accède aux front-ends via
# l'IP LAN de la machine (ex. http://10.158.219.210:3007), et son navigateur
# appelle l'API depuis cette origine — sans cette règle, CORS la bloquerait.
# Plages privées : 10.x, 172.16–31.x, 192.168.x (RFC 1918).
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://(localhost|127\.0\.0\.1):\d+$",
        r"^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+$",
        r"^http://172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}:\d+$",
        r"^http://192\.168\.\d{1,3}\.\d{1,3}:\d+$",
    ]
