# Generated by Django 5.0.14 on 2026-07-18 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Espace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=180, verbose_name="Nom de l'espace"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début d'accès"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fin d'accès"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espaces_diriges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable de l'espace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Espace",
                "verbose_name_plural": "Espaces",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("responsable", "Responsable"),
                            ("formateur", "Formateur"),
                            ("apprenant", "Apprenant"),
                            ("rh", "RH / Recrutement"),
                        ],
                        default="apprenant",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "espace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="espaces.espace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rattachement",
                "verbose_name_plural": "Rattachements",
                "indexes": [
                    models.Index(
                        fields=["espace", "role"], name="espaces_mem_espace__18fb47_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="espaces_mem_user_id_4a50d4_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "espace", "role"),
                name="uniq_membership_user_espace_role",
            ),
        ),
    ]
