# Generated by Django 5.0.14 on 2026-07-20 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=120, unique=True, verbose_name="Clé"),
                ),
                (
                    "value",
                    models.TextField(blank=True, default="", verbose_name="Valeur"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réglage",
                "verbose_name_plural": "Réglages",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="Action"
                    ),
                ),
                (
                    "entite_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Type d'entité",
                    ),
                ),
                (
                    "entite_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Détails"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Horodatage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée d'audit",
                "verbose_name_plural": "Journal d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entite_type", "entite_id"],
                        name="audit_audit_entite__866049_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                ],
            },
        ),
    ]
