# Generated by Django 5.0.14 on 2026-09-03 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dashboard", "Back-office"),
                            ("espace", "Espace apprenant"),
                            ("mobile", "Application mobile"),
                        ],
                        db_index=True,
                        default="dashboard",
                        max_length=16,
                        verbose_name="Origine",
                    ),
                ),
                ("debut", models.DateTimeField(db_index=True, verbose_name="Début")),
                (
                    "derniere_activite",
                    models.DateTimeField(
                        db_index=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "minutes_actives",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minutes actives"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_mesurees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session mesurée",
                "verbose_name_plural": "Temps de connexion",
                "ordering": ["-derniere_activite"],
                "indexes": [
                    models.Index(
                        fields=["user", "-derniere_activite"],
                        name="audit_sessi_user_id_2448ba_idx",
                    )
                ],
            },
        ),
    ]
