# Generated by Django 5.0.14 on 2026-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0021_activityprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
