# Generated by Django 5.0.14 on 2026-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0022_component_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio"),
        ),
        migrations.AddField(
            model_name="component",
            name="audio_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="video"),
        ),
    ]
