# Generated by Django 5.0.14 on 2026-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0023_component_audio_file_component_audio_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputquestionbox",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
