# Generated by Django 5.0.14 on 2026-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0012_remove_publication_meetings_publication_events"),
        ("lessonapp", "0043_alter_activity_a_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="lessonapp.theme"
            ),
        ),
    ]
