# Generated by Django 5.0.14 on 2026-07-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0013_publication_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="acces_duree_mois",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="capacite",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="date_debut",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="date_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="mode",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Session à dates fixes"), (2, "Accès libre")], default=1
            ),
        ),
    ]
