# Generated by Django 5.0.14 on 2026-07-15 22:35

from django.conf import settings
from django.db import migrations, models


def backfill_instructors(apps, schema_editor):
    """L'auteur d'un programme devient animateur des sessions qui le vendent.

    Jusqu'ici le formateur n'était rattaché qu'au programme, et c'est de là que
    découlaient son suivi et son agenda. Sans ce report, la mise en service
    ferait perdre d'un coup à chaque formateur l'accès à ses apprenants.
    Le découpage fin (qui anime mars, qui anime juin) se fait ensuite à la main.
    """
    Publication = apps.get_model("contents", "Publication")
    for pub in Publication.objects.prefetch_related("themes__instructors"):
        ids = {u.id for t in pub.themes.all() for u in t.instructors.all()}
        if ids:
            pub.instructors.add(*ids)


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0014_publication_acces_duree_mois_publication_capacite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="sessions_animees", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(backfill_instructors, migrations.RunPython.noop),
    ]
