# Generated by Django 5.0.14 on 2026-07-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0015_publication_instructors"),
        ("espaces", "0002_espace_maison_mere"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="espaces.espace",
            ),
        ),
    ]
