# Generated by Django 5.0.14 on 2026-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0016_publication_espace"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="show_categorie",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la catégorie"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="show_dates",
            field=models.BooleanField(default=True, verbose_name="Afficher les dates"),
        ),
        migrations.AddField(
            model_name="publication",
            name="show_ecole",
            field=models.BooleanField(default=True, verbose_name="Afficher l'école"),
        ),
        migrations.AddField(
            model_name="publication",
            name="show_places",
            field=models.BooleanField(
                default=True, verbose_name="Afficher les places restantes"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="show_price",
            field=models.BooleanField(default=True, verbose_name="Afficher le prix"),
        ),
    ]
