# Generated by Django 5.0.14 on 2026-07-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0017_publication_show_categorie_publication_show_dates_and_more"),
        ("espaces", "0003_backfill_maison_mere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="espaces.espace",
            ),
        ),
    ]
