# Generated by Django 5.0.14 on 2026-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0018_alter_publication_espace"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="agenda_planification",
            field=models.CharField(
                choices=[
                    (
                        "admin",
                        "Administration seule (formateurs et apprenants consultent)",
                    ),
                    ("formateur", "Formateurs de la session"),
                    ("apprenant", "Formateurs et apprenants de la session"),
                ],
                default="formateur",
                max_length=12,
                verbose_name="Qui planifie l'agenda",
            ),
        ),
    ]
