# Generated by Django 5.0.14 on 2026-07-08 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("objet", models.CharField(max_length=200)),
                ("corps_html", models.TextField()),
                (
                    "corps_texte",
                    models.TextField(
                        blank=True, help_text="Fallback for clients that block HTML."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Declared variables (list of strings) for editor validation.",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Template d'email",
                "verbose_name_plural": "Templates d'emails",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EventConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Requis (toujours actif)"),
                            ("OPTIONAL", "Optionnel (activable)"),
                            ("BLOCKED", "Bloqué (kill-switch)"),
                        ],
                        db_index=True,
                        default="OPTIONAL",
                        max_length=10,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Effectif uniquement quand status=OPTIONAL.",
                    ),
                ),
                (
                    "sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Si vrai, l'admin doit confirmer avant de couper (événement à impact légal ou opérationnel fort).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration d'événement",
                "verbose_name_plural": "Configurations d'événements",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=200)),
                (
                    "corps",
                    models.TextField(
                        help_text="Texte libre (multi-lignes). Le mobile l'affiche tel quel."
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Tous les membres"),
                            ("actifs", "Membres actifs uniquement"),
                            ("suspendus", "Membres suspendus uniquement"),
                            ("selection", "Sélection manuelle (ids)"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=12,
                    ),
                ),
                (
                    "audience_member_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Utilisé uniquement quand audience=selection.",
                    ),
                ),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        help_text="Lien interne optionnel (ex: /campaigns/42) repris sur la notif.",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image illustrative optionnelle (JPG/PNG, recommande 1200x630px). Affichee en haut de la notification mobile et integree dans l'e-mail si diffusion email activee.",
                        null=True,
                        upload_to="coop/announcements/",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Horodatage de diffusion effective (null = pas encore diffusée).",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optionnel : date à laquelle l'annonce devient obsolète.",
                        null=True,
                    ),
                ),
                (
                    "recipients_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de Notifications créées au moment du broadcast.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destinataire", models.EmailField(max_length=254)),
                ("objet", models.CharField(max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("envoye", "Envoyé"),
                            ("echec", "Échec"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("erreur", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="coop_notifications.emailtemplate",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email envoyé",
                "verbose_name_plural": "Emails envoyés",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventHook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail (template)"),
                            ("AUDIT_ONLY", "Audit seulement (silencieux)"),
                        ],
                        default="EMAIL",
                        max_length=16,
                    ),
                ),
                (
                    "target_template_code",
                    models.CharField(
                        blank=True,
                        help_text="Code EmailTemplate à rendre. Si vide, on utilise event.code.",
                        max_length=64,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hooks",
                        to="coop_notifications.eventconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hook d'événement",
                "verbose_name_plural": "Hooks d'événements",
                "ordering": ["event", "ordering"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        help_text="Free-form key, e.g. 'payment.confirmed'.",
                        max_length=64,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        help_text="Optional internal link to the related resource.",
                        max_length=255,
                    ),
                ),
                ("lue", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "lue", "-created_at"],
                        name="coop_notifi_user_id_030490_idx",
                    )
                ],
            },
        ),
    ]
