# Generated by Django 5.0.14 on 2026-07-16 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0019_alter_meeting_link_url"),
        ("lessonapp", "0046_alter_theme_categorie_alter_theme_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="seance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creneaux",
                to="lessonapp.seance",
            ),
        ),
    ]
