# Generated by Django 5.0.14 on 2026-07-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucket", "0018_alter_reservation_event"),
        ("espaces", "0003_backfill_maison_mere"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscriptions",
                to="espaces.espace",
            ),
        ),
    ]
