# Generated by Django 5.0.14 on 2026-07-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucket", "0020_backfill_inscription_espace"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="montant",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
