# Generated by Django 5.0.14 on 2026-07-08 07:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bucket", "0018_alter_reservation_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("INSCRIPTION", "Frais d'inscription"),
                            ("ADHESION", "Frais d'adhésion"),
                            ("DEMANDE_CREDIT", "Frais de demande de crédit"),
                            ("RECONDUCTION", "Frais de reconduction"),
                            ("CARNET", "Frais de carnet"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Type de frais",
                "verbose_name_plural": "Types de frais",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RateParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            (
                                "LOAN_INTEREST",
                                "Taux d'intérêt crédit (par transaction)",
                            ),
                            (
                                "SAVINGS_INTEREST_MONTHLY",
                                "Taux d'intérêt épargne (mensuel)",
                            ),
                            ("RENEWAL_CASH", "Reconduction — intérêts au comptant"),
                            ("RENEWAL_DEFERRED", "Reconduction — intérêts reportés"),
                            ("LATE_PENALTY", "Pénalité de non-versement"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ratio entre 0 et 1 (ex. 0.1000 pour 10 %).",
                        max_digits=6,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taux métier",
                "verbose_name_plural": "Taux métier",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("epargne", "Épargne"),
                            ("epargne_classique", "Épargne classique"),
                            ("frais_inscription", "Frais d'inscription"),
                            ("frais_adhesion", "Frais d'adhésion"),
                            ("frais_demande_credit", "Frais de demande de crédit"),
                            ("frais_reconduction", "Frais de reconduction"),
                            ("frais_carnet", "Frais de carnet"),
                            ("remboursement", "Remboursement"),
                            ("decaissement", "Décaissement"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manuel", "Saisie agence"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("date_versement", models.DateTimeField(db_index=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        help_text="Provider key (e.g. 'tara'). Empty for manual entries.",
                        max_length=24,
                    ),
                ),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Provider transaction id once initiated.",
                        max_length=64,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Prevents duplicate gateway init when the user retries.",
                        unique=True,
                    ),
                ),
                ("gateway_initiated_at", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True)),
                (
                    "is_placement",
                    models.BooleanField(
                        default=False,
                        help_text="Sous-canal épargne classique : True = placement bloqué 12 mois (intérêt mensuel), False = libre (retrait à tout moment).",
                    ),
                ),
                (
                    "nb_jours_couverts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Multi-jours pré-payé pour la collecte (refonte 2026). Défaut 1 = paiement standard.",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_payments",
                        to="bucket.order",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_versement", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fichier", models.FileField(upload_to="coop/payments/%Y/%m/")),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu"),
                            ("capture", "Capture d'écran"),
                            ("rib", "RIB / référence"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                ("taille", models.PositiveIntegerField(default=0)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Justificatif de paiement",
                "verbose_name_plural": "Justificatifs de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["statut", "source"], name="payments_pa_statut_7673e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["member", "-date_versement"],
                name="payments_pa_member__ce968c_idx",
            ),
        ),
    ]
