# Generated by Django 5.0.14 on 2026-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payer_phone",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
