# Generated by Django 5.0.14 on 2026-07-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("image", models.ImageField(upload_to="sitecms/media/")),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Texte alternatif (SEO / accessibilité).",
                        max_length=200,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Mots-clés séparés par des virgules.",
                        max_length=255,
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant d'URL. « accueil » = page d'accueil (/).",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "nav_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé dans le menu (défaut : titre).",
                        max_length=120,
                    ),
                ),
                ("show_in_nav", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sitecms.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("stats", "Statistiques"),
                            ("about", "À propos"),
                            ("services", "Services / cartes"),
                            ("gallery", "Galerie"),
                            ("milestone", "Chiffres-clés (bandeau)"),
                            ("features", "Pourquoi nous / atouts"),
                            ("contact", "Contact"),
                            ("cta", "Appel à l'action"),
                            ("richtext", "Texte riche"),
                        ],
                        default="richtext",
                        max_length=20,
                    ),
                ),
                (
                    "anchor",
                    models.SlugField(
                        blank=True, help_text="Ancre HTML (#services…).", max_length=60
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, help_text="Sur-titre.", max_length=160
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField(blank=True)),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        help_text="Couleur de fond (hex ou token).",
                        max_length=30,
                    ),
                ),
                ("parallax", models.BooleanField(default=False)),
                (
                    "wave",
                    models.BooleanField(
                        default=False,
                        help_text="Séparateur en vague en bas de section.",
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "bg_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sitecms.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="sitecms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'icône Boxicon (ex: bx-target-lock).",
                        max_length=80,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=300)),
                ("link_label", models.CharField(blank=True, max_length=120)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="sitecms.mediaasset",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="sitecms.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_name",
                    models.CharField(
                        default="Human Brain Corporation-RH", max_length=120
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        default="Libérer le potentiel humain", max_length=200
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "phones",
                    models.CharField(
                        blank=True,
                        help_text="Numéros séparés par des virgules.",
                        max_length=255,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Numéro international sans '+' pour wa.me.",
                        max_length=40,
                    ),
                ),
                ("facebook", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("default_meta_title", models.CharField(blank=True, max_length=200)),
                ("default_meta_description", models.TextField(blank=True)),
                (
                    "default_og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sitecms.mediaasset",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sitecms.mediaasset",
                    ),
                ),
                (
                    "logo_white",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sitecms.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages du site",
                "verbose_name_plural": "Réglages du site",
            },
        ),
    ]
