# Generated by Django 5.0.14 on 2026-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="link_label_en",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="card",
            name="text_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="card",
            name="title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="page",
            name="nav_label_en",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="section",
            name="body_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="section",
            name="eyebrow_en",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="section",
            name="subtitle_en",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="section",
            name="title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slogan_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline_en",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
