# Generated by Django 5.0.14 on 2026-07-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecms", "0002_card_link_label_en_card_text_en_card_title_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Résumé affiché dans la liste."
                    ),
                ),
                ("excerpt_en", models.TextField(blank=True)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Corps de l'article (paragraphes séparés par une ligne vide).",
                    ),
                ),
                ("body_en", models.TextField(blank=True)),
                (
                    "author",
                    models.CharField(
                        blank=True, default="Équipe HBC-RH", max_length=120
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=120)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sitecms.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "order", "-created_at"],
            },
        ),
    ]
