# Generated by Django 5.0.14 on 2026-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecms", "0003_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Regroupement (ex: Brochures, Catalogues).",
                        max_length=120,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
