# Generated by Django 5.0.14 on 2026-08-01 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucket", "0022_backfill_inscription_montant"),
        ("sitecms", "0004_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdresseCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_email", models.EmailField(db_index=True, max_length=254)),
                ("nom_complet", models.CharField(blank=True, max_length=200)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("ligne1", models.CharField(blank=True, max_length=255)),
                ("ligne2", models.CharField(blank=True, max_length=255)),
                ("ville", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                (
                    "pays",
                    models.CharField(blank=True, default="Cameroun", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresse_checkout",
                        to="bucket.order",
                    ),
                ),
            ],
        ),
    ]
