# Generated by Django 5.0.14 on 2026-09-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecms", "0006_formationseen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("stats", "Statistiques"),
                    ("about", "À propos"),
                    ("services", "Services / cartes"),
                    ("gallery", "Galerie"),
                    ("milestone", "Chiffres-clés (bandeau)"),
                    ("features", "Pourquoi nous / atouts"),
                    ("contact", "Contact"),
                    ("cta", "Appel à l'action"),
                    ("richtext", "Texte riche"),
                    ("categories", "Formations par catégorie (en direct)"),
                ],
                default="richtext",
                max_length=20,
            ),
        ),
    ]
