# Generated by Django 5.0.14 on 2026-07-14 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0043_alter_activity_a_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="formations_animees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
