# Generated by Django 5.0.14 on 2026-07-15 20:32

from django.db import migrations, models


def backfill_order(apps, schema_editor):
    """Fige l'ordre existant (celui de création) dans le nouveau champ.

    Sans ce backfill tout vaudrait 0, et le tri retomberait sur `id` : le résultat
    serait le même aujourd'hui, mais la première réorganisation d'une séance
    remettrait toutes les autres à un rang arbitraire. On matérialise donc
    l'ordre actuellement affiché, formation par formation / séance par séance.
    """
    Seance = apps.get_model("lessonapp", "Seance")
    Activity = apps.get_model("lessonapp", "Activity")

    for model, parent in ((Seance, "theme_id"), (Activity, "seance_id")):
        rank, current = 0, None
        for obj in model.objects.order_by(parent, "id").only("id", parent):
            key = getattr(obj, parent)
            rank = rank + 1 if key == current else 1
            current = key
            model.objects.filter(pk=obj.pk).update(order=rank)


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0044_theme_instructors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="seance",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="activity",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="seance",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_order, migrations.RunPython.noop),
    ]
