# Generated by Django 5.0.14 on 2026-07-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0045_alter_activity_options_alter_seance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lessonapp.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lessonapp.sequence",
            ),
        ),
    ]
