# Generated by Django 5.0.14 on 2026-07-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espaces", "0002_espace_maison_mere"),
        ("lessonapp", "0046_alter_theme_categorie_alter_theme_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="espaces.espace",
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="espaces.espace",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="espaces.espace",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="espaces.espace",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="themes",
                to="espaces.espace",
            ),
        ),
    ]
