# Generated by Django 5.0.14 on 2026-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0047_categorie_espace_classe_espace_sequence_espace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
