# Generated by Django 5.0.14 on 2026-08-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0048_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="kind",
            field=models.IntegerField(
                choices=[(1, "QCM"), (2, "Vrai/Faux")], default=1
            ),
        ),
    ]
