# Generated by Django 5.0.14 on 2026-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0050_alter_question_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "QCM"),
                    (2, "Vrai/Faux"),
                    (3, "Texte libre"),
                    (4, "Numérique"),
                    (5, "Association"),
                    (6, "Ordonnancement"),
                ],
                default=1,
            ),
        ),
    ]
