# Generated by Django 5.0.14 on 2026-08-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonapp", "0051_alter_question_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="content_updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
