# Generated by Django 5.0.14 on 2026-07-10 09:50

import django.db.models.deletion
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Intitulé du poste"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Département / Pôle"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="Douala — Cameroun",
                        max_length=120,
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("ALTERNANCE", "Alternance"),
                            ("FREELANCE", "Freelance / Mission"),
                        ],
                        default="CDI",
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description du poste")),
                (
                    "profile",
                    models.TextField(blank=True, verbose_name="Profil recherché"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publiée"),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre d'emploi",
                "verbose_name_plural": "Offres d'emploi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Lettre de motivation"),
                ),
                (
                    "cv",
                    models.FileField(
                        upload_to=recruitment.models.cv_upload_to, verbose_name="CV"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nouvelle"),
                            (1, "Vue"),
                            (2, "Présélectionnée"),
                            (3, "Rejetée"),
                        ],
                        default=0,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = candidature spontanée.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="recruitment.joboffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-created_at"],
            },
        ),
    ]
