# Generated by Django 5.0.14 on 2026-07-19 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recruitment_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Évaluation"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernière activité"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Nouvelle"),
                    (1, "Vue"),
                    (2, "Présélectionnée"),
                    (3, "Rejetée"),
                    (4, "Entretien"),
                    (5, "Recrutée"),
                ],
                default=0,
                verbose_name="Statut",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="recruitment.application",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Note de candidature",
                "verbose_name_plural": "Notes de candidature",
                "ordering": ["created_at"],
            },
        ),
    ]
