# Generated by Django 5.0.14 on 2026-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_application_assigned_to_application_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="apply_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name="E-mail de candidature (direct)",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="apply_url",
            field=models.URLField(
                blank=True, verbose_name="Lien de candidature (direct)"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="entreprises/%Y/%m",
                verbose_name="Logo de l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom de l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="company_website",
            field=models.URLField(blank=True, verbose_name="Site de l'entreprise"),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mise en avant"),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="plan",
            field=models.CharField(
                choices=[("classic", "Classique"), ("premium", "Premium")],
                default="classic",
                max_length=10,
                verbose_name="Formule",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="salary",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Rémunération"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="show_closing_date",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la date de clôture"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="show_company",
            field=models.BooleanField(
                default=True, verbose_name="Afficher l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="show_contract",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le type de contrat"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="show_department",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le département"
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="show_location",
            field=models.BooleanField(default=True, verbose_name="Afficher le lieu"),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="show_salary",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la rémunération"
            ),
        ),
    ]
