# Generated by Django 5.0.14 on 2026-07-20 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_joboffer_apply_email_joboffer_apply_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recruteur (compte de suivi)",
            ),
        ),
    ]
